### PR TITLE
Pwd reset redesign

### PR DESCRIPTION
**Pull request by choujar**
Some basic UI redesign based on Gavin's notes for the password reset section.
Had never come across tachyons - still getting the hang of it...

Let me know if there's any rebasing to be done?

Thanks,

Sahil

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Hey @choujar, can I check the expected behaviour here?

Here's what I see:

I get to the signin view:

screen shot 2018-11-20 at 10 06 25


If I don't have the password, I can reset it here

screen shot 2018-11-20 at 10 06 28


Then I get this screen:

screen shot 2018-11-20 at 10 06 20


Is this what you were going for?

Many understanding was that the change requested was for _after_ the reminder email was sent - rather than following a link to the default firebase password reset page, a user would instead end up on the constellate site, and they'd be able to update their password there instead.

This would help address the issue of a user not knowing where to go after they've updated their password.

### Implementing this

I think the way we'd do this would be to 

- customise the the email handler, so we send a link to the constellate app instead of firebase
- implement a form where a user resets the password in the constellate app, _instead_ of the default firebase screen
- allow the user to sign in to the site as usual, presumably with a link back to main url for the site

I've shared a link with Gavin now for him to confirm this - as this was my understanding of it.

## Relevant firebase docs

BTW, this is documentation for taking over the default password handling behaviour for firebase - I think we'd need to add a new route for password reset page, that pulls the relevant GET params form  the url sent in the firebase email. Hope that helps.

https://firebase.google.com/docs/auth/custom-email-handler

**Comment by mrchrisadams** [comment]
Hey @choujar, I've just checked with Gav - and I understand this was just for UI bits.

I've merged this in now - thanks again for your help!

I'm aware there's no documented coding standards, and I don't feel like I can give an objectivecode review without some standard we agree to refer to, otherwise it just sounds like me bike-shedding.

Let's continue that convo in #9 👍

**Comment by choujar** [comment]
@mrchrisadams Thanks for the merge. 

And understood on the password reset - I had no idea that that was the intention.
Gavin's notes seemed to indicate a UI theming fix. I'm going to start implementing what you have indicated above - will confirm with Gavin before I start as well.

**Comment by choujar** [comment]
Oh @mrchrisadams - just noticed - he *has left* notes on the online dev document.

**Pull request merged**
